#pragma once
#include "language_define.h"

enum TEXT_ENUM{
    LANG_SYSTEM,         // "System"
    LANG_DISK,           // "Disk"
    LANG_STATE,          // "State"
    LANG_CHEAT,          // "Cheat"
    LANG_ACHIEVEMENTS,   // "Achievements"
    LANG_BROWSER,        // "Browser"
    LANG_FAVORITE,       // "Favorite"
    LANG_GRAPHICS,       // "Graphics"
    LANG_CONTROL,        // "Control"
    LANG_HOTKEY,         // "Hotkey"
    LANG_CORE,           // "Core"
    LANG_OPTIONS,        // "Options"
    LANG_ABOUT,          // "About"
    LANG_RESUME_GAME,    // "Resume game"
    LANG_RESET_GAME,     // "Reset game"
    LANG_EXIT_GAME,      // "Exit game"
    LANG_BACK_TO_ARCH,   // "Back to Arch"
    LANG_CLEAN_CACHE,    // "Clean Cache"
    LANG_EXIT,           // "Exit App"
    LANG_LANGUAGE,       // "Language"
    LANG_REWIND,         // "Enable Rewind"
    LANG_REWIND_BUF_SIZE, // "Rewind Buffer Size (M)"
    LANG_MUTE,           // "Mute"
    LANG_MOUSE,          // "Simulated Mouse"
    LANG_LIGHTGUN,       // "Simulated Light Gun"
    LANG_SWAP_ENTER,     // "Swap ⇢ ⇣ (Restart Required)"
    LANG_REAR_SIM_BUTTON, // "Simulate ↲↳⇋⇌ with rear touch panel"
    LANG_DISPLAY_SIZE,   // "Display size"
    LANG_ASPECT_RATIO,   // "Aspect ratio"
    LANG_DISPLAY_ROTATE, // "Display rotate"
    LANG_GRAPHICS_SHADER, // "Graphics shader"
    LANG_GRAPHICS_SMOOTH, // "Graphics smooth"
    LANG_OVERLAY_SELECT, // "Overlay select"
    LANG_OVERLAY_MODE,   // "Overlay mode"
    LANG_SHOW_FPS,       // "Show FPS"
    LANG_1X,             // "1X"
    LANG_2X,             // "2X"
    LANG_3X,             // "3X"
    LANG_FULL,           // "Full"
    LANG_BY_GAME_RESOLUTION, // "By game resolution"
    LANG_BY_DEV_SCREEN,  // "By device screen"
    LANG_8_7,            // "8:7"
    LANG_4_3,            // "4:3"
    LANG_3_2,            // "3:2"
    LANG_16_9,           // "16:9"
    LANG_DISABLE,        // "Disable"
    LANG_CW_90,          // "Rotate 90°CW"
    LANG_CW_180,         // "Rotate 180°CW"
    LANG_CW_270,         // "Rotate 270°CW"
    LANG_DEFAULT,        // "Default"
    LANG_LCD3X,          // "LCD3x"
    LANG_SHARP_BILINEAR_SIMPLE, // "Sharp bilinear simple"
    LANG_SHARP_BILINEAR, // "Sharp bilinear"
    LANG_ADVANCED_AA,    // "Advanced AA"
    LANG_MODE_OVERLAY,   // "Overlay"
    LANG_MODE_BACKGROUND, // "Background"
    LANG_NO,             // "No"
    LANG_YES,            // "Yes"
    LANG_TURBO,          // "Turbo"
    LANG_NONE,           // "None"
    LANG_SAVE_STATE,     // "Save state"
    LANG_LOAD_STATE,     // "Load state"
    LANG_GAME_SPEED_UP,  // "Game speed up"
    LANG_GAME_SPEED_DOWN, // "Game speed down"
    LANG_GAME_REWIND,    // "Game rewind"
    LANG_CONTROLLER_PORT_UP, // "Controller port +"
    LANG_CONTROLLER_PORT_DOWN, // "Controller port -"
    LANG_SWITCH_KEYBOARD, // "Switch Keyboard"
    LANG_KEYBOARD_UP,    // "Move keyboard up"
    LANG_KEYBOARD_DOWN,  // "Move keyboard down"
    LANG_MENU_TOGGLE,    // "Menu Toggle"
    LANG_RESET_CONFIGS,  // "Reset configs"
    LANG_COMPILED_ON,    // "Compiled on"
    LANG_AUTHOR,         // "Author"
    LANG_SPECIAL_THANKS, // "Special Thanks"
    LANG_SITE,           // "Site"
    LANG_AUTO_SAVE,      // "Auto Save"
    LANG_EMPTY,          // "Empty"
    LANG_SAVE,           // "Save"
    LANG_LOAD,           // "Load"
    LANG_DELETE,         // "Delete"
    LANG_CANCEL,         // "Cancel"
    LANG_OK,             // "OK"
    LANG_SAVE_CONFIRM,   // "Are you sure you want to overwrite this save state?"
    LANG_LOAD_CONFIRM,   // "Are you sure you want to load this save state?"
    LANG_DELETE_CONFIRM, // "Are you sure you want to delete this save state?"
    LANG_REMOVE_FAVORITE_CONFIRM, // "Are you sure you want to remove this game from your favorites?"
    LANG_CLEAN_CACHE_CONFIRM, // "Are you sure you want to clean the cached files?"
    LANG_EXTERNAL_COMPONENTS, // "External components used by Emu4Vita++"
    LANG_ENTER_DIR,      // "Enter dir "
    LANG_BACK_DIR,       // "Back dir"
    LANG_START_GAME,     // "Start game"
    LANG_ADD_FAVORITE,   // "Add to favorites"
    LANG_REMOVE_FAVORITE, // "Remove from favorites"
    LANG_SEARCH,         // "Search"
    LANG_NEXT,           // "Next"
    LANG_FILE_MANAGE,    // "File Manage"
    LANG_COPY,           // "Copy"
    LANG_CUT,            // "Cut"
    LANG_PASTE,          // "Paste"
    LANG_RENAME,         // "Rename"
    LANG_CORE_NOTICE,    // "After changing the settings, reset the game to take effect"
    LANG_ENABLED,        // "enabled"
    LANG_DISABLED,       // "disabled"
    LANG_LOAD_ROM_FAILED, // "Failed to load rom，press any key to continue"
    LANG_MOUSE_FRONT_TOUCH_PANEL, // "Front touch panel + ↜ ↝"
    LANG_MOUSE_REAR_TOUCH_PANEL, // "Rear touch panel + ↜ ↝"
    LANG_UNSET,          // "Unset"
    LANG_DEVICE_PORT,    // "Device port "
    LANG_FOUND,          // "Found"
    LANG_NOT_FOUND,      // "Not found"
    LANG_FILE,           // "file"
    LANG_FILES,          // "files"
    CODE,                // "en"
    LANG_INDEPENDENT_CONFIG, // "Independent config"
    LANG_DELETE_FILE_CONFIRM, // "Are you sure you want to delete this file?"
    LANG_OVERWRITE_FILE_CONFIRM, // "A file with the same name exists. Overwrite it?"
    LANG_SAME_DIR_WARN,  // "Cannot paste in the same directory"
    LANG_DELETED,        // "File deleted"
    LANG_DELETION_FAILED, // "File deletion failed"
    LANG_SPEED,          // "Game speed"
    LANG_INSERT_DISK,    // "Insert this disk?"
    LANG_MISSING_BIOS,   // "Missing BIOS files:"
    LANG_MAX,            // "Max"
    LANG_SPEED_STEP,     // "Speed Step"
    LANG_JAPANESE_TRANS, // "Japanese translation"
    LANG_ITALIAN_TRANS,  // "Italian translation"
    LANG_FRENCH_TRANS,   // "French translation"
    LANG_SPANISH_TRANS,  // "Spanish translation"
    LANG_START_CORE_NO_GAME, // "Start core without content"
    LANG_NEW_VERSION_AVAILABLE, // "A new version is available"
    LANG_RUSSIAN_TRANS,  // "Russian translation"
    LANG_AUTO_ROTATING,  // "Auto rotating for vertical games"
    LANG_DOWNLOAD_THUMBNAILS, // "Download Thumbnails"
    LANG_DOWNLOAD_PROGRESS, // "Download progress"
    LANG_PRESS_CANCEL,   // "Press %s to cancel"
    LANG_ZERO_DOWNLOAD,  // "No images were downloaded"
    LANG_ONE_DOWNLOAD,   // "Downloaded one image"
    LANG_MANY_DOWNLOAD,  // "Downloaded %d images"
    LANG_AUTO_LOAD,      // "Auto Load"
    LANG_RETROACHIEVEMENTS, // "RetroAchievements"
    LANG_RETROACHIEVEMENTS_DESC, // "If you don't know what this is, visit https://retroachievements.org"
    LANG_HARDCORE,       // "Hardcore mode"
    LANG_HARDCORE_DESC,  // "Disables load/save states, cheats, rewind and slow-motion."
    LANG_USERNAME,       // "Username"
    LANG_PASSWORD,       // "Password"
    LANG_NO_NETWORK,     // "No active network connection"
    LANG_LOGIN_SUCCESSFUL, // "Login successful"
    LANG_LOGIN_FAILED,   // "Login failed"
    LANG_TOKEN_EXPIRED,  // "The token of RetroAchievements has expired. Please login again."
    LANG_ACHIEVEMENT_UNLOCKED, // "Achievement Unlocked"
    LANG_LEADERBOARD_STARTED, // "Leaderboard attempt started"
    LANG_LEADERBOARD_FAILED, // "Leaderboard attempt failed"
    LANG_LEADERBOARD_SUBMITTED, // "Leaderboard submitted"
    LANG_RETROARCHIEVEMENTS_LOCAL, // "Achievement display location"
    LANG_TOP_LEFT,       // "Top left"
    LANG_TOP_RIGHT,      // "Top right"
    LANG_BOTTOM_LEFT,    // "Bottom left"
    LANG_BOTTOM_RIGHT,   // "Bottom right"
    LANG_GAME_COMPLETED, // "Game Completed"
    LANG_RETROACHIEVEMENTS_TESTER, // "RetroAchievements Tester"
    LANG_CPU_FREQ,       // "CPU frequency"
    LANG_AUTO,           // "Auto"
    LANG_AUDIO_LATENCY,  // "Audio Latency (ms)"
    LANG_FRONT_SIM_BUTTON, // "Simulate ↲↳⇋⇌ with front touch screen"
    LANG_TEST,           // "Test"
    LANG_HOLD_EXIT,      // "Press and hold %s to exit."
    LANG_RETROACHIEVEMENTS_ADMIN, // "RetroAchievements Admin"
    LANG_THEME,          // "Theme"
    TEXT_COUNT,
};


#define TRANSLATION_COUNT 621
